# Generated by Django 5.0.3 on 2024-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('languages', models.CharField(max_length=100)),
                ('dbms', models.CharField(max_length=100)),
                ('softwares', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
